### ISSUE TITLE
Add large file support

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/beyond-ftp#10]
We read all content into memory for now, it's not acceptable for real users. 

The logic looks the same as https://github.com/beyondstorage/beyond-fs/blob/master/vfs/cache.go, maybe we can extract it as a new library.

**Comment by Xuanwo** [comment]
I'm working the lib: https://github.com/beyondstorage/go-converge

<blockquote><img src="https://opengraph.githubassets.com/c110c727e330d55807d6c2437a60f38664cd90fdc46239cfd8c5196f3408e1ff/beyondstorage/go-converge" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-converge">beyondstorage/go-converge</a></strong></div><div>A lib that converge input from upperlying storage to underlying storage. - beyondstorage/go-converge</div></blockquote>

**Comment by Xuanwo** [comment]
Hi @xiongjiwei, the 0.1.0 version for go-stream has been released: https://github.com/beyondstorage/go-stream/releases/tag/v0.1.0

Could you give it a try?

<blockquote><img src="https://opengraph.githubassets.com/206cc355bf145b9882b7d35803d0c81c2ea000e13270752a6cd35166ecbd7eed/beyondstorage/go-stream" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/beyondstorage/go-stream/releases/tag/v0.1.0">Release v0.1.0 · beyondstorage/go-stream</a></strong></div><div>v0.1.0 - 2021-08-23
Added

feat: Implement basic stream logic (#1)
feat: Implement stream logic via Multipart (#4)
feat: Add check for multipart (#7)
test: Implement integration tests (#8)
feat: Ad...</div></blockquote>

**Comment by xiongjiwei** [comment]
that's great

**Comment by xiongjiwei** [comment]
Hi @Xuanwo, seems it only supports `storager` which implements `Multiparter`, maybe I should wait for the `PersistMethodWrite PersistMethod` to be supported?

**Comment by Xuanwo** [comment]
> Hi @Xuanwo, seems it only supports `storager` which implements `Multiparter`, maybe I should wait for the `PersistMethodWrite PersistMethod` to be supported?

I think it's OK to add support for `Multipart` first.

**Comment by xiongjiwei** [comment]
Got a question about the `stream` lib, does it support append data to the under storager？ How can I control the behavior to append or overwrite? I find the `PersistMethodAppend` which seems will be implemented in the future. if I should use this field to control the `stream` behavior, seems I should create 2 streams, one is used for overwriting and another one is used for append.

**Comment by Xuanwo** [comment]
The go-storage design limited that:

- We can't `append` an object unless the object is created by `CreateAppend`, aka, has `Append` object mode.
- We can't do multipart on an object unless the object is created by `CreateMultipart`, aka, has `Multipart` object mode.

The limitation is introduced by most storage services (except local fs) can't support append to object.

So, we always need to choose a persist mode before we start to create the file. And it's could be `PersistMethodMutlipart` or `PersistMethodAppend`, of course, multipart only for now.

It's OK for BeyondFTP to return errors if the underlying storage doesn't have append supports.
